// Code generated by ent, DO NOT EDIT.

package ticket

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the ticket type in the database.
	Label = "ticket"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBookingID holds the string denoting the booking_id field in the database.
	FieldBookingID = "booking_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPassengerName holds the string denoting the passenger_name field in the database.
	FieldPassengerName = "passenger_name"
	// FieldPassengerLicenseID holds the string denoting the passenger_license_id field in the database.
	FieldPassengerLicenseID = "passenger_license_id"
	// FieldPassengerEmail holds the string denoting the passenger_email field in the database.
	FieldPassengerEmail = "passenger_email"
	// FieldSeatNumber holds the string denoting the seat_number field in the database.
	FieldSeatNumber = "seat_number"
	// FieldClass holds the string denoting the class field in the database.
	FieldClass = "class"
	// EdgeBooking holds the string denoting the booking edge name in mutations.
	EdgeBooking = "booking"
	// Table holds the table name of the ticket in the database.
	Table = "tickets"
	// BookingTable is the table that holds the booking relation/edge.
	BookingTable = "tickets"
	// BookingInverseTable is the table name for the Booking entity.
	// It exists in this package in order to avoid circular dependency with the "booking" package.
	BookingInverseTable = "bookings"
	// BookingColumn is the table column denoting the booking relation/edge.
	BookingColumn = "booking_id"
)

// Columns holds all SQL columns for ticket fields.
var Columns = []string{
	FieldID,
	FieldBookingID,
	FieldStatus,
	FieldPassengerName,
	FieldPassengerLicenseID,
	FieldPassengerEmail,
	FieldSeatNumber,
	FieldClass,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusCanceled  Status = "Canceled"
	StatusDeparted  Status = "Departed"
	StatusScheduled Status = "Scheduled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusCanceled, StatusDeparted, StatusScheduled:
		return nil
	default:
		return fmt.Errorf("ticket: invalid enum value for status field: %q", s)
	}
}

// Class defines the type for the "class" enum field.
type Class string

// Class values.
const (
	ClassFirstClass    Class = "FirstClass"
	ClassBusinessClass Class = "BusinessClass"
	ClassEconomyClass  Class = "EconomyClass"
)

func (c Class) String() string {
	return string(c)
}

// ClassValidator is a validator for the "class" field enum values. It is called by the builders before save.
func ClassValidator(c Class) error {
	switch c {
	case ClassFirstClass, ClassBusinessClass, ClassEconomyClass:
		return nil
	default:
		return fmt.Errorf("ticket: invalid enum value for class field: %q", c)
	}
}

// OrderOption defines the ordering options for the Ticket queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBookingID orders the results by the booking_id field.
func ByBookingID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBookingID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPassengerName orders the results by the passenger_name field.
func ByPassengerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassengerName, opts...).ToFunc()
}

// ByPassengerLicenseID orders the results by the passenger_license_id field.
func ByPassengerLicenseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassengerLicenseID, opts...).ToFunc()
}

// ByPassengerEmail orders the results by the passenger_email field.
func ByPassengerEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassengerEmail, opts...).ToFunc()
}

// BySeatNumber orders the results by the seat_number field.
func BySeatNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeatNumber, opts...).ToFunc()
}

// ByClass orders the results by the class field.
func ByClass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClass, opts...).ToFunc()
}

// ByBookingField orders the results by booking field.
func ByBookingField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBookingStep(), sql.OrderByField(field, opts...))
	}
}
func newBookingStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BookingInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BookingTable, BookingColumn),
	)
}
