services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 9999:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: flookybooky
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passwd

  user:
    profiles: ["user", "graphql"]
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./grpc/user-grpc/user.dockerfile
    restart: on-failure
    ports:
      - 4001:4000

  flight:
    profiles: ["flight", "graphql"]
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./grpc/flight-grpc/flight.dockerfile
    restart: on-failure
    ports:
      - 4003:4000

  customer:
    profiles: ["customer", "graphql"]
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./grpc/customer-grpc/customer.dockerfile
    restart: on-failure
    ports:
      - 4002:4000

  booking:
    profiles: ["booking", "graphql"]
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./grpc/booking-grpc/booking.dockerfile
    restart: on-failure
    ports:
      - 4004:4000

  graphql:
    profiles: ["graphql"]
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - 4000:4000
      - 8081:8081
