package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	internal "flookybooky/internal/parser"
	"flookybooky/model"
)

// Ticket is the resolver for the ticket field.
func (r *queryResolver) Ticket(ctx context.Context, input *model.Pagination) ([]*model.Ticket, error) {
	ticketsRes, err := r.client.BookingClient.GetTickets(ctx,
		internal.ParsePaginationGraphqlToPb(input))
	return internal.ParseTicketsPbToGraphqlTo(ticketsRes), err
}
