// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"flookybooky/ent/airport"
	"flookybooky/ent/flight"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FlightCreate is the builder for creating a Flight entity.
type FlightCreate struct {
	config
	mutation *FlightMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (fc *FlightCreate) SetCreatedAt(t time.Time) *FlightCreate {
	fc.mutation.SetCreatedAt(t)
	return fc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fc *FlightCreate) SetNillableCreatedAt(t *time.Time) *FlightCreate {
	if t != nil {
		fc.SetCreatedAt(*t)
	}
	return fc
}

// SetUpdatedAt sets the "updated_at" field.
func (fc *FlightCreate) SetUpdatedAt(t time.Time) *FlightCreate {
	fc.mutation.SetUpdatedAt(t)
	return fc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fc *FlightCreate) SetNillableUpdatedAt(t *time.Time) *FlightCreate {
	if t != nil {
		fc.SetUpdatedAt(*t)
	}
	return fc
}

// SetName sets the "name" field.
func (fc *FlightCreate) SetName(s string) *FlightCreate {
	fc.mutation.SetName(s)
	return fc
}

// SetOriginID sets the "origin_id" field.
func (fc *FlightCreate) SetOriginID(u uuid.UUID) *FlightCreate {
	fc.mutation.SetOriginID(u)
	return fc
}

// SetDestinartionID sets the "destinartion_id" field.
func (fc *FlightCreate) SetDestinartionID(u uuid.UUID) *FlightCreate {
	fc.mutation.SetDestinartionID(u)
	return fc
}

// SetDepartureTime sets the "departure_time" field.
func (fc *FlightCreate) SetDepartureTime(t time.Time) *FlightCreate {
	fc.mutation.SetDepartureTime(t)
	return fc
}

// SetArrivalTime sets the "arrival_time" field.
func (fc *FlightCreate) SetArrivalTime(t time.Time) *FlightCreate {
	fc.mutation.SetArrivalTime(t)
	return fc
}

// SetTotalSlots sets the "total_slots" field.
func (fc *FlightCreate) SetTotalSlots(i int) *FlightCreate {
	fc.mutation.SetTotalSlots(i)
	return fc
}

// SetAvailableSlots sets the "available_slots" field.
func (fc *FlightCreate) SetAvailableSlots(i int) *FlightCreate {
	fc.mutation.SetAvailableSlots(i)
	return fc
}

// SetStatus sets the "status" field.
func (fc *FlightCreate) SetStatus(f flight.Status) *FlightCreate {
	fc.mutation.SetStatus(f)
	return fc
}

// SetID sets the "id" field.
func (fc *FlightCreate) SetID(u uuid.UUID) *FlightCreate {
	fc.mutation.SetID(u)
	return fc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (fc *FlightCreate) SetNillableID(u *uuid.UUID) *FlightCreate {
	if u != nil {
		fc.SetID(*u)
	}
	return fc
}

// SetOrigin sets the "origin" edge to the Airport entity.
func (fc *FlightCreate) SetOrigin(a *Airport) *FlightCreate {
	return fc.SetOriginID(a.ID)
}

// SetDestinationID sets the "destination" edge to the Airport entity by ID.
func (fc *FlightCreate) SetDestinationID(id uuid.UUID) *FlightCreate {
	fc.mutation.SetDestinationID(id)
	return fc
}

// SetDestination sets the "destination" edge to the Airport entity.
func (fc *FlightCreate) SetDestination(a *Airport) *FlightCreate {
	return fc.SetDestinationID(a.ID)
}

// Mutation returns the FlightMutation object of the builder.
func (fc *FlightCreate) Mutation() *FlightMutation {
	return fc.mutation
}

// Save creates the Flight in the database.
func (fc *FlightCreate) Save(ctx context.Context) (*Flight, error) {
	fc.defaults()
	return withHooks(ctx, fc.sqlSave, fc.mutation, fc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FlightCreate) SaveX(ctx context.Context) *Flight {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fc *FlightCreate) Exec(ctx context.Context) error {
	_, err := fc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fc *FlightCreate) ExecX(ctx context.Context) {
	if err := fc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fc *FlightCreate) defaults() {
	if _, ok := fc.mutation.CreatedAt(); !ok {
		v := flight.DefaultCreatedAt()
		fc.mutation.SetCreatedAt(v)
	}
	if _, ok := fc.mutation.UpdatedAt(); !ok {
		v := flight.DefaultUpdatedAt()
		fc.mutation.SetUpdatedAt(v)
	}
	if _, ok := fc.mutation.ID(); !ok {
		v := flight.DefaultID()
		fc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FlightCreate) check() error {
	if _, ok := fc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Flight.created_at"`)}
	}
	if _, ok := fc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Flight.updated_at"`)}
	}
	if _, ok := fc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Flight.name"`)}
	}
	if _, ok := fc.mutation.OriginID(); !ok {
		return &ValidationError{Name: "origin_id", err: errors.New(`ent: missing required field "Flight.origin_id"`)}
	}
	if _, ok := fc.mutation.DestinartionID(); !ok {
		return &ValidationError{Name: "destinartion_id", err: errors.New(`ent: missing required field "Flight.destinartion_id"`)}
	}
	if _, ok := fc.mutation.DepartureTime(); !ok {
		return &ValidationError{Name: "departure_time", err: errors.New(`ent: missing required field "Flight.departure_time"`)}
	}
	if _, ok := fc.mutation.ArrivalTime(); !ok {
		return &ValidationError{Name: "arrival_time", err: errors.New(`ent: missing required field "Flight.arrival_time"`)}
	}
	if _, ok := fc.mutation.TotalSlots(); !ok {
		return &ValidationError{Name: "total_slots", err: errors.New(`ent: missing required field "Flight.total_slots"`)}
	}
	if _, ok := fc.mutation.AvailableSlots(); !ok {
		return &ValidationError{Name: "available_slots", err: errors.New(`ent: missing required field "Flight.available_slots"`)}
	}
	if _, ok := fc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Flight.status"`)}
	}
	if v, ok := fc.mutation.Status(); ok {
		if err := flight.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Flight.status": %w`, err)}
		}
	}
	if _, ok := fc.mutation.OriginID(); !ok {
		return &ValidationError{Name: "origin", err: errors.New(`ent: missing required edge "Flight.origin"`)}
	}
	if _, ok := fc.mutation.DestinationID(); !ok {
		return &ValidationError{Name: "destination", err: errors.New(`ent: missing required edge "Flight.destination"`)}
	}
	return nil
}

func (fc *FlightCreate) sqlSave(ctx context.Context) (*Flight, error) {
	if err := fc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	fc.mutation.id = &_node.ID
	fc.mutation.done = true
	return _node, nil
}

func (fc *FlightCreate) createSpec() (*Flight, *sqlgraph.CreateSpec) {
	var (
		_node = &Flight{config: fc.config}
		_spec = sqlgraph.NewCreateSpec(flight.Table, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeUUID))
	)
	if id, ok := fc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := fc.mutation.CreatedAt(); ok {
		_spec.SetField(flight.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := fc.mutation.UpdatedAt(); ok {
		_spec.SetField(flight.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := fc.mutation.Name(); ok {
		_spec.SetField(flight.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := fc.mutation.DepartureTime(); ok {
		_spec.SetField(flight.FieldDepartureTime, field.TypeTime, value)
		_node.DepartureTime = value
	}
	if value, ok := fc.mutation.ArrivalTime(); ok {
		_spec.SetField(flight.FieldArrivalTime, field.TypeTime, value)
		_node.ArrivalTime = value
	}
	if value, ok := fc.mutation.TotalSlots(); ok {
		_spec.SetField(flight.FieldTotalSlots, field.TypeInt, value)
		_node.TotalSlots = value
	}
	if value, ok := fc.mutation.AvailableSlots(); ok {
		_spec.SetField(flight.FieldAvailableSlots, field.TypeInt, value)
		_node.AvailableSlots = value
	}
	if value, ok := fc.mutation.Status(); ok {
		_spec.SetField(flight.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := fc.mutation.OriginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.OriginTable,
			Columns: []string{flight.OriginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OriginID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := fc.mutation.DestinationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   flight.DestinationTable,
			Columns: []string{flight.DestinationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(airport.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DestinartionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FlightCreateBulk is the builder for creating many Flight entities in bulk.
type FlightCreateBulk struct {
	config
	builders []*FlightCreate
}

// Save creates the Flight entities in the database.
func (fcb *FlightCreateBulk) Save(ctx context.Context) ([]*Flight, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Flight, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FlightMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FlightCreateBulk) SaveX(ctx context.Context) []*Flight {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fcb *FlightCreateBulk) Exec(ctx context.Context) error {
	_, err := fcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcb *FlightCreateBulk) ExecX(ctx context.Context) {
	if err := fcb.Exec(ctx); err != nil {
		panic(err)
	}
}
